name: HTML Accessibility Check

on:
  workflow_call:
    inputs:
      target_url:
        default: https://spacetelescope.github.io/${{ github.event.repository.name }}
        description: "URL to scan"
        required: false
        type: 'string'
    secrets:
      A11YWATCH_TOKEN:
        description: 'a11ywatch token'
        required: false
  workflow_dispatch:
    inputs:
      target_url:
        default: null
        description: "URL to scan"
        required: false
        type: 'string'
        

jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Web Accessibility Evaluation of ${{ inputs.target_url }}
        uses: a11ywatch/github-actions@v2.1.10
        with:
          WEBSITE_URL: ${{ inputs.target_url }}
          SITE_WIDE: true
          SUBDOMAINS: true
          SITEMAP: true
          UPGRADE: true
          LIST: true
          EXTERNAL: true
          UPLOAD: true
          FAIL_ERRORS_COUNT: 1
          A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
