name: HTML Accessibility Check

on:
  workflow_call:
    inputs:
      target_url:
        default: https://spacetelescope.github.io/${{ github.event.repository.name }}
        description: "URL to scan"
        required: false
        type: 'string'
    secrets:
      A11YWATCH_TOKEN:
        description: 'a11ywatch token'
        required: false
  workflow_dispatch:
    inputs:
      target_url:
        default: null
        description: "URL to scan"
        required: false
        type: 'string'
        

jobs:
  a11yWatchRun:
    runs-on: ubuntu-latest
    steps:
      - name: Run PEP8 style check
        run: |
          curl --location --request POST 'https://api.a11ywatch.com/api/crawl' --header 'Authorization: ${{ secrets.A11YWATCH_TOKEN }}' --header 'Content-Type: application/json'   -d '{ "url": "${{ inputs.target_url }}" }' > blarg.json
          cat blarg.json

